server :
  port : 8070

application :
  version: 1.0.0
  title : thejoeun company

spring:
  datasource:
    generate-unique-name: false
    
#    MySQL 연결
#    url: jdbc:mysql://localhost:3306/mydb  # mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234

#    MariaDB 연결
    url: jdbc:mariadb://localhost:3306/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

#    Oracle 연결
#    url: jdbc:oracle:thin:@localhost:1521:xe  # Oracle
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: root
#    password: 1234

#    H2 Database 연결
#  url: jdbc:h2:mem:testdb     # H2 Embeded Memory
#  driver-class-name: org.h2.Driver  # H2 connect driver
#  username: sa
#  password :

  jpa:
    show-sql: true
    defer-datasource-initialization: true # data.sql 사용을 위해서 필수적으로 등록
    properties:
      hibernate:
        format_sql: true  # SQL문을 pretty하게 보여줌
        use_sql_comments: true  # 주석을 달아주는 친구
#    generate-ddl: true   # true , false  ## JPA 영역 ### ddl-auto 가 있으면 이거 없어도됨
    hibernate:
      ddl-auto: create   # create, create-drop, update , validate, none
  sql:
    init:
      mode: always  # always : embeded db가 아닌 외부 db 사용시 spring boot를 실행할때 마다 data.sql schema.sql import.sql 을 실행시켜준다.
#                    # never :  data.sql schema.sql import.sql 을 실행하지않음.
#      encoding: utf-8   # 한글안나올때 써줌
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true

#logging:
#  level:
#    org:
#
##      hibernate: trace
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
#        SQL: debug
##        SQL : debug
##        type : trace
##    root: trace
