server :
  port : 8070

application :
  version: 1.0.0
  title : thejoeun company

spring:
  datasource:
    generate-unique-name: false
  h2:
    console:
      path : /h2-console
      url : jdbc:h2:mem:testdb
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true # data.sql 사용을 위해서 필수적으로 등록
    properties:
      hibernate:
        format_sql: true  # SQL문을 pretty하게 보여줌
#    generate-ddl: false
#    hibernate:
#      ddl-auto: create-drop   # ddl(create, drop)
#  sql:
#    init:
#      mode: always
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
