--insert into member(`id`, `name`, `email`, `create_at`, `update_at`) values (6, '유관순1', 'ryukwansun@thejoeun.com', now(), now());
--insert into member(`id`, `name`, `email`, `create_at`, `update_at`) values (7, '유관순2', 'yukwansun@thejoeun.com', now(), now());
